### ISSUE TITLE
Apply Daft Doris Logo top left

### ISSUE THREAD

**Issue by chrisns** [chrisns/smartseven#90]
![daft doris logo](https://user-images.githubusercontent.com/104105362/164709412-0715f529-92ac-4b9b-91ef-33946f2d339f.svg)

**Comment by chrisns** [comment]
@mrjamieeast please could you provide the logo here, svg preferably?

**Comment by mrjamieeast** [comment]
Jamie East
THE SMART 7
T: +44 7515 340555
@jamieeast
www.thesmart7.com
Listen to the latest episode <http://podfollow.com/thesmart7>
