### ISSUE TITLE
Change font (not inputted text) to Goole font bree Serif

### ISSUE THREAD

**Issue by chrisns** [chrisns/smartseven#92]

**Comment by chrisns** [comment]
@mrjamieeast what do you mean by the 'not inputted text'? what text do you want changed?

**Comment by mrjamieeast** [comment]
Sorry - was trying to think of. A way of describing it.
All text that isn’t text inputted into fields of longer list/long list and script.

So the numbers, the title of Longer List etc. the text in the input box before you type.


Jamie East
THE SMART 7
T: +44 7515 340555
@jamieeast
www.thesmart7.com
Listen to the latest episode <http://podfollow.com/thesmart7>
